services:
  mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - app-network
    depends_on:
      - mongo

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - MONGO_URI=mongodb://localhost:27017/CellPhoneStore
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - ELASTICSEARCH_HOST=http://localhost:9200
    depends_on:
      - mongo
      - redis
      - elasticsearch
    networks:
      - app-network
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./www
      dockerfile: Dockerfile
    environment:
      - REACT_APP_FRONTEND_URL=http://localhost:3000
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network

  elasticsearch:
    image: elastic/elasticsearch:8.15.5
    volumes:
      - ./docker-elk/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro,Z
      - ./docker-elk/elasticsearch:/usr/share/elasticsearch/data:Z
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      node.name: elasticsearch
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      ELASTIC_PASSWORD: REPLIES-aiming-linking-milan-dessert
      discovery.type: single-node
    networks:
      - app-network
    restart: unless-stopped

volumes:
  mongo-data:
    driver: local
  elasticsearch:


networks:
  app-network:
    driver: bridge
