
GET http://localhost:8080/api/v1
Authorization: Bearer undefined

###
GET http://localhost:8080/

### register
POST http://localhost:8080/api/v1/users/register
Content-Type: application/json

{
    "email": "khanhmh2004@gmail.com",
    "password": "123456",
    "confirmPassword": "123456",
    "username": "khanh"
}



### update user
PATCH http://localhost:8080/api/v1/users/update
Content-Type: application/json

{
    "email": "khanhmh2004@gmail.com",
    "username": "khanh123",
    "password": "12345678"
}

### forgot password
POST http://localhost:8080/api/v1/users/forgotPassword
Content-Type: application/json

{
    "email": "khanhmh2004@gmail.com"
}

### reset password

POST http://localhost:8080/api/v1/users/resetPassword
Content-Type: application/json

{
    "password": "duykhanh123",
    "token": "801905ec480ea2be26165056e166408b9831560c6b04d7134bc3cd738f87b93a"
}


### verify otp
POST http://localhost:8080/api/v1/users/verifyAccount
Content-Type: application/json

{
    "email": "khanhmh2004@gmail.com",
    "otp": "821547"
}


### login
POST http://localhost:8080/api/v1/users/login
Content-Type: application/json

{
    "email": "khanhmh2004@gmail.com",
    "password": "12345678"
}


### login
GET  http://localhost:8080/login/google


### login
POST http://localhost:8080/api/v1/users/login
Content-Type: application/json

{
    "email": {"$gte":""},
    "password": {"$gte":""}
}

### 
POST http://localhost:8080/api/v1/users/refresh-token
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImtoYW5obWgyMDA0QGdtYWlsLmNvbSIsInVzZXJJZCI6IjY3NDJmYTM5NTY4NDIwYjdkOGMxN2IzNSIsImlhdCI6MTczMjQ2MTI0NywiZXhwIjoxNzY0MDE4ODQ3fQ.TXbM_X43sEBb27XipVVV7_KoW-H2fzILhutbPIWybm94g1HuYr9vvoGyrZxxKFLPzp545AUL4RxKaXinsfUS78anMBV1iijeexYEUWql_Nl2bGFQ0HRa28Pyi5JGZIMaT8HAL4zlbmFu30aAhTikbuSNhw_1OlU7jIMDMynR0PFOqGZ2l7YZTmj-sCij4dboiVOfWDwCLr7h94A8V6qgdvpW94aaHLytAxMucqV9rifnSqaXSlCbtlT-Q0sLdeNIbxUZ8-zbHarTJZJPKz1ts1wZvgl02ucrPA5UhL4WRFlBdMVmb8FcITPHzBghTmRb7BnarUZPTiwUDg_MUBFdFm95iYHDEA1dn7RTzmuyfIvzgpHf28LcZBMAgF3oqMDBTI8_FV-z1Un3JTjC3LOIBTZjfzGuJ1-JO0eh55QK46NP79Oo11kjHqpIRjU0UF2zbkFYXgP3fg3-7m6vUwSG4wqwh42SPvtk5NlHvJoPhCesvqeD5z4jXFK5zcIvUXjWvECT9meyyd2Sr1KkF_OslLOxBflofpWQSfbcag-Uv4jSWZKUGGyMt9gAYgvrcB_iyJS1D4I9ZFf7t_WOvF8sj_1vFQE1dtPQvgT8wFr3pDznif-rBrOnf8-1C_955afIzCJw_1mVIvmkXtBFQ1WZaYqcFbqyPN7vDqXqUgJBfBM"
}


### logout
DELETE http://localhost:8080/api/v1/users/logout
Content-Type: application/json

### get user
GET http://localhost:8080/api/v1/users
Authorization: Bearer undefined


### pageign products
GET  http://localhost:8080/api/v1/products/page/


### get products
GET  http://localhost:8080/api/v1/products/?sort=price_asc&q=phone


### delete product
DELETE  http://localhost:8080/api/v1/products/671d20bf6d0cf9d25a89e9f


###
POST  http://localhost:8080/api/v1/products/
Content-Type: application/json

{
    "name": "3 afklsadfkasdfk",
    "price": "2",
    "category": "ipad",
    "stock": "123",
    "image": "upload.jpg"
}


### get cart
POST  http://localhost:8080/api/v1/cart
Content-Type: application/json

{

    "productId": "6746a87e968e3c7eaeb4d9a5",
    "quantity": 3,
    "variantId": "671b1fda58ec0d68f0625601"
     
}

### get shipping
POST  http://localhost:8080/api/v1/cart/shipping-fee
Content-Type: application/json

{
    "shippingAddress": {
        "city": "Bình Dương",
        "district": "Huyện Dầu Tiếng"
    }
}

###
POST  http://localhost:8080/api/v1/coupons
Content-Type: application/json

{
    "code": "e123122",
    "discount": 1000000,
    "expiryDate": "2025-09-30",
    "description": "123456",
    "type": "fixed",
    "quantity": 100,
    "condition": {
        "minOrderValue": 50,
        "applicableCategories": ["electronics", "fashion"]
    }
}


###
PATCH  http://localhost:8080/api/v1/orders/6752ac01c271faeca8d67eb7/rating
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImtoYW5obWgyMDA0QGdtYWlsLmNvbSIsInVzZXJJZCI6IjY3NGM3YzY1OGZjN2E5YTliZjQ3NjIzYyIsInJvbGUiOiJjdXN0b21lciIsInVzZXJuYW1lIjoiRHV5IEtoYW5oIiwiaWF0IjoxNzMzNDc5MjIzLCJleHAiOjE3MzM0NzkyODN9.V4V856jk1RdOYt5iOniZXDPqt5e75VMmnWTqLMuy44kEcvydmJd6YxbXFRJI3F_EWOaNBWNymBnSw2cjsMAYbKiF9Yn9Lxy6VDyeWDVEVbdpbL1_aNm7ttqg7983Lr0TFLrbfuKIMnsmyjDYT_c-WPsUK_uXiCJccwNQNvbObAmIYlbRzU5ZJDfv3eK7TBr6bLOv1dOuNQZ2ohlh_H0ptlryjQoltCfP3H2uI9MditXBoPa_ZsGs_MlBgyORGO4l0CSsEwIvvwyKcWNUW63KUGYvLVpB72Tk3kNEhusS4xStHOf-8CkS_H0ACYquAFHQ6iWESaIRUfVZcbeIoAJOWW1x2UdKrMeiroP4fkRlh-hqsaqplwniNPpwaWQcUVnI7YOxOvlCnGLmkhV_xn-tg7b5uGmCNNQWbZ1ItEFmrUyVqDuxJwj1DijePi7SWZnrcTxN71TRd_hEXICcq5Q81LdPGPZ4bLOknijt_xbfBRK_ADlSEuheeIzQKUl9f42NGo6irSgwmK5SFehRuYch7l_1PD3he5rLHESIuf6SL1AkNbAs2psVzKVOwM7Id17FxCREzYfNqYIj7MJ5x7edjYKJbOzZEjN7qc8YBJBJ6PHroPwSr8BTVnbqT62EQNDzGtr17q-qurZ2I_2TWWqfCDQO7fnKB1_85K_-1IVjUew

{
    "ratings": [
        { "productId": 3, "star": 4, "review": "Great product!" },
        { "productId": 4, "star": 5, "review": "Great product!" },
        { "productId": 5, "star": 3, "review": "Great product!" }
    ]
}


###
GET http://localhost:8080/api/v1/products/search