services:
  elasticsearch:
    image: elasticsearch:8.16.1@sha256:c5ea110d0a644fbfaaf44ab1d16612e510b2f977afc333aa261d981a8af12784
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - node.name=elasticsearch
      - cluster.name=datasearch
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS="-Xms512m -Xmx512m"
      - cluster.initial_master_nodes=elasticsearch
    healthcheck:
      test: [ "CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1" ]
      interval: 10s
      timeout: 10s
      retries: 3
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - elastic

  kibana:
    image: kibana:8.16.1@sha256:9e7acb4155627f28c22393035c665a25584cf572e99c49d77151146de305620d
    container_name: kib
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - elastic

networks:
  elastic:
    driver: bridge
