
GET http://localhost:8080/api/v1
Authorization: Bearer undefined

###
GET http://localhost:8080/

### register
POST http://localhost:8080/api/v1/users/register
Content-Type: application/json

{
    "email": "khanhmh2004@gmail.com",
    "password": "123456",
    "confirmPassword": "123456",
    "username": "khanh"
}



### update user
PATCH http://localhost:8080/api/v1/users/update
Content-Type: application/json

{
    "email": "khanhmh2004@gmail.com",
    "username": "khanh123",
    "password": "12345678"
}

### forgot password
POST http://localhost:8080/api/v1/users/forgotPassword
Content-Type: application/json

{
    "email": "khanhmh2004@gmail.com"
}

### reset password

POST http://localhost:8080/api/v1/users/resetPassword
Content-Type: application/json

{
    "password": "duykhanh123",
    "token": "801905ec480ea2be26165056e166408b9831560c6b04d7134bc3cd738f87b93a"
}


### verify otp
POST http://localhost:8080/api/v1/users/verifyAccount
Content-Type: application/json

{
    "email": "khanhmh2004@gmail.com",
    "otp": "821547"
}


### login
POST http://localhost:8080/api/v1/users/login
Content-Type: application/json

{
    "email": "khanhmh2004@gmail.com",
    "password": "123456"
}


### login
GET  http://localhost:8080/login/google


### login
POST http://localhost:8080/api/v1/users/login
Content-Type: application/json

{
    "email": {"$gte":""},
    "password": {"$gte":""}
}

### 
POST http://localhost:8080/api/v1/users/refresh-token
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImtoYW5obWgyMDA0QGdtYWlsLmNvbSIsInVzZXJJZCI6IjY3NDJmYTM5NTY4NDIwYjdkOGMxN2IzNSIsImlhdCI6MTczMjQ2MTI0NywiZXhwIjoxNzY0MDE4ODQ3fQ.TXbM_X43sEBb27XipVVV7_KoW-H2fzILhutbPIWybm94g1HuYr9vvoGyrZxxKFLPzp545AUL4RxKaXinsfUS78anMBV1iijeexYEUWql_Nl2bGFQ0HRa28Pyi5JGZIMaT8HAL4zlbmFu30aAhTikbuSNhw_1OlU7jIMDMynR0PFOqGZ2l7YZTmj-sCij4dboiVOfWDwCLr7h94A8V6qgdvpW94aaHLytAxMucqV9rifnSqaXSlCbtlT-Q0sLdeNIbxUZ8-zbHarTJZJPKz1ts1wZvgl02ucrPA5UhL4WRFlBdMVmb8FcITPHzBghTmRb7BnarUZPTiwUDg_MUBFdFm95iYHDEA1dn7RTzmuyfIvzgpHf28LcZBMAgF3oqMDBTI8_FV-z1Un3JTjC3LOIBTZjfzGuJ1-JO0eh55QK46NP79Oo11kjHqpIRjU0UF2zbkFYXgP3fg3-7m6vUwSG4wqwh42SPvtk5NlHvJoPhCesvqeD5z4jXFK5zcIvUXjWvECT9meyyd2Sr1KkF_OslLOxBflofpWQSfbcag-Uv4jSWZKUGGyMt9gAYgvrcB_iyJS1D4I9ZFf7t_WOvF8sj_1vFQE1dtPQvgT8wFr3pDznif-rBrOnf8-1C_955afIzCJw_1mVIvmkXtBFQ1WZaYqcFbqyPN7vDqXqUgJBfBM"
}


### logout
DELETE http://localhost:8080/api/v1/users/logout
Content-Type: application/json


### pageign products
GET  http://localhost:8080/api/v1/products/page/


### get products
GET  http://localhost:8080/api/v1/products/?sort=price_asc&q=phone


### delete product
DELETE  http://localhost:8080/api/v1/products/671d20bf6d0cf9d25a89e9f


###
POST  http://localhost:8080/api/v1/products/
Content-Type: application/json

{
    "name": "3 afklsadfkasdfk",
    "price": "2",
    "category": "ipad",
    "stock": "123",
    "image": "upload.jpg"
}


### get cart
POST  http://localhost:8080/api/v1/cart
Content-Type: application/json

{

    "productId": "671b1fda58ec0d68f0625600",
    "quantity": 324234,
    "variantId": "671b1fda58ec0d68f0625601"
     
}
