
GET http://localhost:8080/api/v1

###
GET http://localhost:8080/

### register
POST http://localhost:8080/api/v1/users/register
Content-Type: application/json

{
    "email": "khanhmh2004@gmail.com",
    "password": "123456",
    "username": "khanh"
}


### update user
PATCH http://localhost:8080/api/v1/users/update
Content-Type: application/json

{
    "email": "khanhmh2004@gmail.com",
    "username": "khanh123",
    "password": "12345678"
}

### forgot password
POST http://localhost:8080/api/v1/users/forgotPassword
Content-Type: application/json

{
    "email": "khanhmh2004@gmail.com"
}

### reset password

POST http://localhost:8080/api/v1/users/resetPassword
Content-Type: application/json

{
    "password": "duykhanh123",
    "token": "801905ec480ea2be26165056e166408b9831560c6b04d7134bc3cd738f87b93a"
}


### verify otp
POST http://localhost:8080/api/v1/users/verifyAccount
Content-Type: application/json

{
    "email": "khanhmh2004@gmail.com",
    "otp": "196475"
}


### login
POST http://localhost:8080/api/v1/users/login
Content-Type: application/json

{
    "email": "khanhmh2004@gmail.com",
    "password": "duykhanh123"
}


### login
GET  http://localhost:8080/login/google


### login
POST http://localhost:8080/api/v1/users/login
Content-Type: application/json

{
    "email": {"$gte":""},
    "password": {"$gte":""}
}

### 
POST http://localhost:8080/api/v1/users/refresh-token
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImtoYW5obWgyMDA0QGdtYWlsLmNvbSIsInVzZXJJZCI6IjY3MTI3MGJjYWY4YTA5MzgwNTVlYzg1NyIsImlhdCI6MTcyOTM1NDQyMywiZXhwIjoxNzYwOTEyMDIzfQ.RouB8mBJ3IIEsqmOReX7eq4fwp5LQE-N_nxlFfa5haFwmLvY53o7bf9Ipj8FkXqOXb5sVQhDGpJHmpi5Nu2Q47Lsmci1Y5GKoY1P0CuxshoQePlEBjAo9Be8XhVvqnWgQ0Xinze5Clxj6Rizeig7nDnJ3Q-J49zjkLBCVrDJgF3BEcMianLYEmIpaptn5I1kD9mKA8dAghpYpDWJNDpfQ8s7T5zuXIe6eWQxMaFFanaznm3AdiJ27h9tbXuXDawNttu94Z0cyE2kbU4RNUN1fLQkSG1Qj-Gt7fmiRBKZvNPTT0QlfgVytbwJZR6H6UcNrzTVjU2HDGYU-SNQxPkQjKxe9qBqZJKa7LQp-t5VJhE9Nig4prCAQo2df_C4V-lkwfwdQwF56Elm7da5PTec1oILwSAnDbXHd_01R0d6lkAfWxV71-0lzq7hP25zRFi70au4QdMVLJLR4qOnf9sKBzoWhQshHKgOydVNsrFkeHwLX5soNPa_UYc0g8xq7uNpAYiv6DAdJuvledfDA6gZaiAsRSgbTMqKox6tkHVXjXA5LixerbcOSNI7Lnb_B7sBRvwR29sS44wfQ8UaHmrgQrJmskFZ0reaspMYsZ3OOpMYokg39Qe3Lnayay3QqdDQdONXtr9RwiJiE3T5P_85gQG3vlzhUiNxsIx1zwRW3aY"
}


### logout
DELETE http://localhost:8080/api/v1/users/logout
Content-Type: application/json


### pageign products
GET  http://localhost:8080/api/v1/products/page/?after=671bb83c08d03b3f04e011da


###
POST  http://localhost:8080/api/v1/products/
Content-Type: application/json

{
    "name": "3 afklsadfkasdfk",
    "price": "2",
    "category": "ipad",
    "stock": "123",
    "image": "upload.jpg"
}