name: Code quality

on:
  push:
  pull_request:

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: latest

        # Frontend code quality
      - name: Move to the project directory
        run: cd www && biome ci src/ --fix --unsafe

        # Backend code quality
      - name: Move to the project directory
        run: cd ../server && biome ci src/ --fix --unsafe
