name: Code quality

on:
  push:
  pull_request:

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: latest

        # Frontend code quality
      - name: Move to the project directory
        run: cd www && biome check --write --formatter-enabled=true --linter-enabled=true --organize-imports-enabled=true src/

        # Backend code quality
      - name: Move to the project directory
        run: cd ../server && biome check --write --formatter-enabled=true --linter-enabled=true --organize-imports-enabled=true src/
